#!/usr/bin/env python3
"""PTY end-to-end boot-contract suite for the pi-tui TUI.

Boots the REAL installed `dsh` CLI against a temp DSH_HOME profile that pulls
the local @jianxx bundles (synced from this repo's lib/) plus a scripted mock
LLM, then drives three scenarios inside a real PTY:

  a. boot + first key: title renders, a prompt streams MOCK OK, /quit exits 0,
     and the cursor-restore escape \\x1b[?25h is emitted on shutdown.
  b. frame overflow: an 80-line flood (taller than the terminal) renders, then
     a later prompt still gets MOCK OK — the composer stayed alive.
  c. resize: three mid-run TIOCSWINSZ resizes do not crash the process.

Python stdlib only (pty/select/termios). No new root npm deps.
"""
import fcntl
import json
import os
import pty
import re
import select
import shutil
import signal
import struct
import subprocess
import sys
import tempfile
import termios
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[5]
MOCK_LLM = ROOT / "packages" / "ui" / "tui" / "tests" / "e2e" / "mock-llm.mjs"
PROFILE = "e2e-cc-tui"
TITLE = "dsh cc-mode"
COLS = 100
ROWS = 30


def make_home() -> Path:
    home = Path(tempfile.mkdtemp(prefix="dsh-tui-e2e-"))
    (home / "profiles").mkdir(parents=True)
    # Reuse the installer-maintained @deepseek-ai fallback so published deps
    # (dsh-base, cordis, …) resolve exactly as in a real profile. Read-only
    # link into ~/.dsh — never writes there.
    fallback = Path.home() / ".dsh" / "profiles" / "node_modules"
    (home / "profiles" / "node_modules").symlink_to(fallback)
    return home


def bootstrap(home: Path) -> Path:
    """Write the profile package.json, build lib/, sync @jianxx packages in,
    and emit the patch overlay that inserts the mock-llm plugin row."""
    pdir = home / "profiles" / PROFILE
    pdir.mkdir(parents=True, exist_ok=True)
    (pdir / "package.json").write_text(
        json.dumps(
            {
                "name": "dsh-profile-e2e-cc-tui",
                "private": True,
                "dependencies": {},
                "dsh": {
                    "profile": {
                        "bundles": [
                            "@deepseek-ai/dsh-base",
                            "@jianxx/dsh-cc-bundle-permissions",
                            "@jianxx/dsh-cc-bundle-shell",
                            "@jianxx/dsh-cc-bundle-tui",
                        ]
                    }
                },
            },
            indent=2,
        )
        + "\n"
    )

    # Fresh lib/ so the synced copy matches the source we are testing.
    subprocess.run(["pnpm", "run", "build"], cwd=str(ROOT), check=True)
    env = dict(os.environ)
    env["DSH_HOME"] = str(home)
    subprocess.run(
        ["bash", "scripts/sync-local-profile.sh", PROFILE],
        cwd=str(ROOT),
        env=env,
        check=True,
    )

    patch = home / "e2e.patch.yml"
    patch.write_text(
        "# generated by packages/ui/tui/scripts/e2e/run_core.py\n"
        "- insert:\n"
        "    - id: e2e-mock-llm\n"
        f"      name: '{MOCK_LLM}'\n"
    )
    return patch


class TuiSession:
    """One dsh boot inside a PTY, with a minimal query-answering terminal."""

    def __init__(self, label: str, home: Path, patch: Path, extra_env=None, rows=ROWS, cols=COLS) -> None:
        self.label = label
        self.transcript = bytearray()
        self.answered: set[str] = set()
        env = dict(os.environ)
        env["DSH_HOME"] = str(home)
        env["DSH_CC_PROVIDER"] = "mock"
        env["DSH_CC_MODEL"] = "e2e-1"
        env["TERM"] = "xterm-256color"
        env["COLUMNS"] = str(cols)
        env["LINES"] = str(rows)
        env["NODE_ENV"] = "production"
        if extra_env:
            env.update(extra_env)
        self.cmd = ["dsh", "--profile", PROFILE, "--patch", str(patch)]
        self.master, slave = pty.openpty()
        self._set_winsize(slave, rows, cols)
        os.set_inheritable(slave, True)
        self._stderr_path = Path(f"/tmp/dsh-tui-e2e-{label}.stderr")
        self._stderr = open(self._stderr_path, "w")
        self.proc = subprocess.Popen(
            self.cmd,
            stdin=slave,
            stdout=slave,
            stderr=self._stderr,
            env=env,
            cwd=str(ROOT),
            close_fds=True,
            preexec_fn=os.setsid,
        )
        os.close(slave)

    @staticmethod
    def _set_winsize(fd: int, rows: int, cols: int) -> None:
        fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", rows, cols, 0, 0))

    def resize(self, rows: int, cols: int) -> None:
        # The pty pair shares one winsize; setting it on the master propagates
        # SIGWINCH to the slave's foreground process group.
        self._set_winsize(self.master, rows, cols)

    def _answer_queries(self, chunk: bytes) -> None:
        replies = []
        if b"\x1b[c" in chunk or b"\x1b[0c" in chunk:
            replies.append(b"\x1b[?62;22c")
        for _ in re.findall(rb"\x1b\[6n", chunk):
            replies.append(b"\x1b[40;1R")
        if (b"\x1b]11;?" in chunk) and ("osc11" not in self.answered):
            self.answered.add("osc11")
            replies.append(b"\x1b]11;rgb:1e1e/1e1e/1e1e\x1b\\")
        if b"\x1b[?2026$p" in chunk:
            replies.append(b"\x1b[?2026;2$y")
        if replies:
            os.write(self.master, b"".join(replies))

    def flat(self) -> str:
        t = bytes(self.transcript).decode("utf-8", "replace")
        t = re.sub(r"\x1b\[[0-9]*C", " ", t)
        t = re.sub(r"\x1b\[[0-9;?<>=]*[A-Za-z]", "", t)
        t = re.sub(r"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)", "", t)
        t = re.sub(r"[\r\n]+", " ", t)
        return re.sub(r"\s+", " ", t)

    def read_until(self, needles: list[str], timeout: float) -> str | None:
        deadline = time.time() + timeout
        while time.time() < deadline:
            r, _, _ = select.select([self.master], [], [], 0.25)
            if self.master in r:
                try:
                    chunk = os.read(self.master, 65536)
                except OSError:
                    break
                if not chunk:
                    break
                self.transcript.extend(chunk)
                self._answer_queries(chunk)
            flat = self.flat()
            for needle in needles:
                if needle in flat:
                    return needle
            if self.proc.poll() is not None:
                try:
                    while True:
                        chunk = os.read(self.master, 65536)
                        if not chunk:
                            break
                        self.transcript.extend(chunk)
                except OSError:
                    pass
                break
        flat = self.flat()
        for needle in needles:
            if needle in flat:
                return needle
        return None

    def drain(self, seconds: float) -> None:
        end = time.time() + seconds
        while time.time() < end:
            r, _, _ = select.select([self.master], [], [], 0.2)
            if self.master in r:
                try:
                    chunk = os.read(self.master, 65536)
                except OSError:
                    return
                if not chunk:
                    return
                self.transcript.extend(chunk)
                self._answer_queries(chunk)
            if self.proc.poll() is not None:
                return

    def send(self, data: bytes) -> None:
        try:
            os.write(self.master, data)
        except OSError:
            # Process exited / pty closed — nothing more to send.
            pass

    def type_line(self, text: bytes) -> None:
        self.send(text)
        self.drain(0.5)
        if text.startswith(b"/"):
            # A bare slash word opens the completion menu, whose Enter ACCEPTS
            # instead of submitting; Esc dismisses it first.
            self.send(b"\x1b")
            self.drain(0.3)
        self.send(b"\r")

    def finish(self) -> None:
        try:
            if self.proc.poll() is None:
                self.type_line(b"/quit")
                self.drain(2.0)
            try:
                self.proc.wait(timeout=20)
            except subprocess.TimeoutExpired:
                pass
        finally:
            if self.proc.poll() is None:
                try:
                    os.killpg(self.proc.pid, signal.SIGKILL)
                except OSError:
                    pass
            try:
                os.close(self.master)
            except OSError:
                pass
            try:
                self._stderr.close()
            except OSError:
                pass
            Path(f"/tmp/dsh-tui-e2e-{self.label}.transcript").write_bytes(bytes(self.transcript))


def report(label: str, ok: bool, failures: list[str]) -> None:
    print(f"  {'PASS' if ok else 'FAIL'}  {label}")
    if not ok:
        failures.append(label)


def scenario_a(home: Path, patch: Path, failures: list[str]) -> None:
    print("\n[scenario a] boot + first key")
    s = TuiSession("a", home, patch)
    try:
        if not s.read_until([TITLE], 60):
            report("a title rendered", False, failures)
            return
        s.drain(0.5)
        s.type_line(b"hello world")
        report("a mock reply streamed", s.read_until(["MOCK OK"], 45) is not None, failures)
        s.drain(0.5)
        s.type_line(b"/quit")
        s.drain(2.0)
    finally:
        s.finish()
    raw = bytes(s.transcript)
    report("a title rendered", TITLE in s.flat(), failures)
    report("a mock reply present", "MOCK OK" in s.flat(), failures)
    report("a exited cleanly", s.proc.poll() == 0, failures)
    report("a cursor restored", b"\x1b[?25h" in raw[-3000:], failures)


def scenario_b(home: Path, patch: Path, failures: list[str]) -> None:
    print("\n[scenario b] frame overflow keeps composer alive")
    s = TuiSession("b", home, patch, extra_env={"DSH_CC_E2E_LINES": "80"})
    try:
        if not s.read_until([TITLE], 60):
            report("b title rendered", False, failures)
            return
        s.drain(0.5)
        s.type_line(b"flood")
        report("b flood completed", s.read_until(["e2e line 80"], 45) is not None, failures)
        s.drain(1.0)
        s.type_line(b"ping")
        report("b composer alive after overflow", s.read_until(["MOCK OK"], 45) is not None, failures)
        s.drain(0.5)
        s.type_line(b"/quit")
        s.drain(2.0)
    finally:
        s.finish()
    report("b title rendered", TITLE in s.flat(), failures)
    report("b flood completed", "e2e line 80" in s.flat(), failures)
    report("b composer alive after overflow", "MOCK OK" in s.flat(), failures)
    report("b exited cleanly", s.proc.poll() == 0, failures)


def scenario_c(home: Path, patch: Path, failures: list[str]) -> None:
    print("\n[scenario c] resize keeps process alive")
    s = TuiSession("c", home, patch)
    crashed = False
    try:
        if not s.read_until([TITLE], 60):
            report("c title rendered", False, failures)
            return
        s.drain(0.5)
        s.type_line(b"resize-probe")
        report("c initial reply streamed", s.read_until(["MOCK OK"], 45) is not None, failures)
        s.drain(1.0)
        for rows, cols in [(24, 80), (40, 120), (30, 100)]:
            s.resize(rows, cols)
            s.drain(1.0)
            if s.proc.poll() is not None:
                crashed = True
                report(f"c no crash after resize to {rows}x{cols}", False, failures)
                break
        if not crashed:
            s.type_line(b"/quit")
            s.drain(2.0)
    finally:
        s.finish()
    report("c title rendered", TITLE in s.flat(), failures)
    report("c no crash after 3 resizes", not crashed, failures)
    report("c exited cleanly", s.proc.poll() == 0, failures)


def run() -> int:
    home = make_home()
    try:
        patch = bootstrap(home)
        failures: list[str] = []
        scenario_a(home, patch, failures)
        scenario_b(home, patch, failures)
        scenario_c(home, patch, failures)
        if failures:
            print(f"\ne2e FAILED: {failures}")
            # Transcripts/stderr for each scenario were written to /tmp by
            # TuiSession.finish for triage.
            print(f"DSH_HOME: {home}")
            print("transcripts: /tmp/dsh-tui-e2e-{a,b,c}.transcript")
            return 1
        print("\ne2e PASSED")
        return 0
    finally:
        # Keep the temp DSH_HOME on disk for post-run triage (it lives under
        # the OS temp dir, so it is cleaned automatically over time).
        pass


if __name__ == "__main__":
    sys.exit(run())
